var config = {
    apiKey: "AIzaSyCxjZqhAWrp3vf_wanuS7_iYem_1eLattA",
    authDomain: "inpatient-8a288.firebaseapp.com",
    databaseURL: "https://inpatient-8a288.firebaseio.com",
    storageBucket: "inpatient-8a288.appspot.com",
    messagingSenderId: "607664151265"
};
firebase.initializeApp(config);

inPatientDatabase = firebase.database();

$(document).ready(function(){

    $("#single_patient").hide();

    inPatientDatabase.ref().on("child_added", function(childSnapshot){
        //current child key generated by firebase
        var patient_Database_Key = childSnapshot.key;

        //screenshots of current information by child
        var first_name = childSnapshot.val().first_name;
        var last_name = childSnapshot.val().last_name;
        var gender = childSnapshot.val().gender;
        var DOB = childSnapshot.val().DOB;
        var phone = childSnapshot.val().phone;

        //fixing variables
        var whole_name = (first_name + " " + last_name).toUpperCase();
        DOB = moment(DOB).format("MM/DD/YYYY");

        //create appropriate divs and columns
        var button_key = $("<button class='patient_button waves-effect waves-teal btn-flat blue-grey'>" + whole_name + "</button>").attr("data-key", patient_Database_Key);
        var completed_button = $("<div class='col m3'>").append(button_key);
        var gender_col_m3 = $("<div class='col m3'>").text(gender);
        var DOB_col_m3 = $("<div class='col m3'>").text(DOB);
        var phone_col_m3 = $("<div class='col m3'>").text(phone);
        var div_Row = $("<div class='row'>");
        var completed_patient_Div = div_Row.append(completed_button).append(
                                    gender_col_m3).append(DOB_col_m3).append(
                                    phone_col_m3);

        $("#patient_list").append(completed_patient_Div);

        //on button click event
        $(button_key).on("click", function(event) {
            event.preventDefault();
            var key = $(this).data("key");

            $("#all_patients").hide();
            $("#single_patient").show();

            inPatientDatabase.ref().child(key).once('value').then(function(snapshot){
                var patient = snapshot.val();
                console.log(snapshot.val().first_name);

                $("#info_holder").append(snapshot.val().first_name);

                //code to display patient info here

            });
        });

    });

});
